name: 📆 Scheduled Vocab Trigger

on:
  schedule:
    - cron: "30 17 * * *"  # Runs daily at 9:30 AM PST / 17:30 UTC
  workflow_dispatch:  # Manual trigger option

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Run vocab trigger
      run: python trigger_vocab.py
